### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by ahao1995** [ChistyakovArtem/CMF_HFMM#1]
Sorry to bother you, Is there any origin data can upload, TechCore/data dir is empy, thanks!

**Comment by ChistyakovArtem** [comment]
I will give link to google drive, yes. The data is too big to paste it here

**Comment by ahao1995** [comment]
thanks!!!

**Comment by ahao1995** [comment]
I read the code and have another question, I see delay = pd.Timedelta(0.1, 's').delta only 100ms, I think it is too short, so I want to know why choose 100ms to hold orders

**Comment by ChistyakovArtem** [comment]
We agreed to hold only 1 order in each side in each time. So if we dont executed (our order) in 100ms - we place new one.

**Comment by ChistyakovArtem** [comment]
Check here for data
https://github.com/ChistyakovArtem/CMF_HFMM/tree/main/TechCore/Data
